services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: dEqSzzszVzDwDocveDZVIQaPuhjMWugv
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data